config/routes.rb
Rails.application.routes.draw do
  
  root "books#index"

  resources :books do
    member do
      get :delete
    end
  end

  # get 'books/index'
  # get 'books/new'
  # get 'books/edit'
  # get 'books/delete'
  # get 'books/show'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/book.rb
class Book < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
    @books = Book.all
  end

  def show
    @book = Book.find(params[:id])
  end

  def new
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)
    if @book.save
      flash[:notice] = 'Book was successfully added to collection...'
      redirect_to books_path
    else
      render('new')
    end
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      flash[:notice] = 'Book was successfully modified...'
      redirect_to books_path
    else
      render('edit')
    end
  end

  def delete
    @book = Book.find(params[:id])
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    flash[:notice] = 'Book was successfully removed from collection...'
    redirect_to books_path
  end

  private

  def book_params
    params.require(:book).permit(
      :title,
      :author,
      :published_date,
      :price
    )
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_helper.rb
module BookHelper
end

app/views/books/delete.html.erb
<div class="books delete">
    <h2>Remove Book</h2>

    <%= form_for(@book, method: 'delete') do |f| %>

        <p>Are you sure you want to permanently remove this book?</p>

        <p>
            <strong>Title:</strong>
            <%= @book.title %><br />
            <strong>Author:</strong>
            <%= @book.author %><br />
        </p>

        <div class="form-buttons">
            <%= f.submit("Remove Book From Collection") %>
        </div>

    <% end %>


    <div>
        <%= link_to("Back to books", books_path, class: 'back-link') %>
    </div>
</div>

app/views/books/edit.html.erb
<div class="books edit">
    <h2>Edit Book</h2>

    <%= form_for(@book) do |f| %>
        <p>
            <strong>Title:</strong>
            <%= f.text_field(:title) %><br />
            <strong>Author:</strong>
            <%= f.text_field(:author) %><br />
            <strong>Published:</strong>
            <%= f.date_field(:published_date) %><br />
            <strong>Price:</strong>
            <%= f.text_field(:price) %><br />
        </p>

        <div class="form-buttons">
            <%= f.submit("Edit Book") %>
        </div>
    <% end %>

    <div>
        <%= link_to("Back to books", books_path, class: 'back-link') %>
    </div>
</div>

app/views/books/index.html.erb
<style>
  table {
    border-collapse: collapse;
  }

  th, td {
    padding: 8px;
    text-align: left;
    border-bottom: 1px solid #ddd;
  }
</style>

<h1>Books</h1>

<p style="color: green"><%= notice %></p>

<div id="books">
    <% @books.each do |book| %>
        <table>
            <tr>
                <th>Title</th>
                <td><%= book.title %></td>
            </tr>
            <tr>
                <th>Author</th>
                <td><%= book.author %></td>
            </tr>
            <tr>
                <th>Published</th>
                <td><%= book.published_date %></td>
            </tr>
            <tr>
                <th>Price</th>
                <td><%= book.price %></td>
            </tr>
        </table>


        <div class="actions" style="display: flex;">
            <%= link_to("Show this book", book_path(book), class: 'action show') %>
            <div style="width: 15px; display: inline-block;"></div> <!-- Spacer -->
            <%= link_to("Edit this book", edit_book_path(book), class: 'action edit') %>
            <div style="width: 15px; display: inline-block;"></div> <!-- Spacer -->
            <%= link_to("Remove this book", delete_book_path(book), class: 'action delete') %>
        </div>
    <% end %>
</div> <br />

<%= link_to("New book", new_book_path, class: 'action new') %>

app/views/books/new.html.erb
<div class="books new">
    <h2>Add Book</h2>

    <%= form_for(@book) do |f| %>
        <p>
            <strong>Title:</strong>
            <%= f.text_field(:title) %><br />
            <strong>Author:</strong>
            <%= f.text_field(:author) %><br />
            <strong>Published:</strong>
            <%= f.date_field(:published_date) %><br />
            <strong>Price:</strong>
            <%= f.text_field(:price) %><br />
        </p>

        <div class="form-buttons">
            <%= f.submit("Add Book to Collection") %>
        </div>
    <% end %>

    <div>
        <%= link_to("Back to books", books_path, class: 'back-link') %>
    </div>
</div>

app/views/books/show.html.erb
<div class="books show">
    <h2>Book Details</h2>

    <p>
        <strong>Title:</strong>
        <%= @book.title %><br />
        <strong>Author:</strong>
        <%= @book.author %><br />
        <strong>Published:</strong>
        <%= @book.published_date %><br />
        <strong>Price:</strong>
        <%= @book.price %><br />
    </p>

    <div>
        <%= link_to("Edit this book", edit_book_path(@book)) %>
        <%= link_to("Remove this book", delete_book_path(@book)) %>
        <%= link_to("Back to books", books_path, class: 'back-link') %>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BookCollection</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>